export const mockUser = {
  id: 'user-1',
  name: 'Jane Writer',
  email: 'jane.writer@example.com',
  emailVerified: true,
  image: '/default-profile.png',
  bio: 'I am a writer from somewhere in the USA.',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),

  books: [
    {
      id: 1,
      title: 'The Honey Trail',
      author: 'Jane Writer',
      genre: 'Adventure',
      category: 'Fiction',
      description: 'A book about bees and adventure.',
      coverImage: '/default-book-cover.png',
      privacy: 'Public',
      // lastEditedBy: 'user-1',
      createdAt: new Date().toISOString(),
      publishedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      status: 'In Progress',
      wordCount: 32000,
      userId: 'user-1',
      chapters: [
        {
          id: 1,
          title: 'A New Hive',
          author: 'Jane Writer',
          notes: 'Intro to the world',
          content: 'Once upon a time...',
          privacy: 'Public',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2500,
          comments: [
            {
              id: 1,
              content: 'Great start!',
              createdAt: new Date().toISOString(),
              chapterId: 1,
              authorId: '33',
              author: { id: '11', name: 'Alex Friend' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 2,
              content: 'Love the setting.',
              createdAt: new Date().toISOString(),
              chapterId: 1,
              authorId: '33',
              author: { id: '11', name: 'Sam Bee' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 3,
              content: "Can't wait for more!",
              createdAt: new Date().toISOString(),
              chapterId: 1,
              authorId: '33',
              author: { id: '11', name: 'Chris Reader' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
        {
          id: 2,
          title: 'The Swarm',
          author: 'Jane Writer',
          notes: 'The bees gather.',
          content: 'The bees gathered...',
          privacy: 'Public',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 3000,
          comments: [
            {
              id: 4,
              content: 'Exciting chapter!',
              createdAt: new Date().toISOString(),
              chapterId: 2,
              authorId: '3',
              author: { id: '11', name: 'Pat Honey' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 5,
              content: 'Nice pacing.',
              createdAt: new Date().toISOString(),
              chapterId: 2,
              authorId: '33',
              author: { id: '11', name: 'Taylor Buzz' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 6,
              content: 'Looking forward to the next!',
              createdAt: new Date().toISOString(),
              chapterId: 2,
              authorId: '33',
              author: { id: '11', name: 'Morgan Hive' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
        {
          id: 3,
          title: "Queen's Decision",
          author: 'Jane Writer',
          notes: 'A turning point.',
          content: 'The queen must decide...',
          privacy: 'Public',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 3500,
          comments: [
            {
              id: 7,
              content: 'Dramatic!',
              createdAt: new Date().toISOString(),
              chapterId: 3,
              authorId: '33',
              author: { id: '11', name: 'Jamie Nectar' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 8,
              content: 'Great character development.',
              createdAt: new Date().toISOString(),
              chapterId: 3,
              authorId: '33',
              author: { id: '11', name: 'Robin Flower' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 9,
              content: 'So much suspense!',
              createdAt: new Date().toISOString(),
              chapterId: 3,
              authorId: '333',
              author: { id: '11', name: 'Casey Pollen' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
      ],
      comments: [],
      collaborators: [
        { id: '4', name: 'Alex Friend' },
        { id: '4', name: 'Sam Bee' },
      ],
    },
    // Book 2
    {
      id: 2,
      title: 'Bee Adventures',
      author: 'Jane Writer',

      genre: 'Adventure',
      category: 'Fiction',
      description: 'More bee stories.',
      coverImage: '/default-book-cover.png',
      privacy: 'Private',
      // lastEditedBy: 'user-1',
      createdAt: new Date().toISOString(),
      publishedAt: undefined,
      updatedAt: new Date().toISOString(),
      status: 'In Progress',
      wordCount: 28000,
      userId: 'user-1',
      chapters: [
        {
          id: 4,
          title: 'The Journey Begins',
          author: 'Jane Writer',
          notes: '',
          content: 'A new journey...',
          privacy: 'Private',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2000,
          comments: [
            {
              id: 10,
              content: 'Nice start!',
              createdAt: new Date().toISOString(),
              chapterId: 4,
              authorId: '33',
              author: { id: '11', name: 'Drew Clover' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 11,
              content: 'Very descriptive.',
              createdAt: new Date().toISOString(),
              chapterId: 4,
              authorId: '33',
              author: { id: '11', name: 'Sky Willow' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 12,
              content: "Can't wait for more.",
              createdAt: new Date().toISOString(),
              chapterId: 4,
              authorId: '33',
              author: { id: '11', name: 'Alex Friend' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
        {
          id: 5,
          title: 'Into the Wild',
          author: 'Jane Writer',
          notes: '',
          content: 'Exploring the wild...',
          privacy: 'Private',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2500,
          comments: [
            {
              id: 13,
              content: 'Love the adventure.',
              createdAt: new Date().toISOString(),
              chapterId: 5,
              authorId: '33',
              author: { id: '11', name: 'Sam Bee' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 14,
              content: 'Great imagery.',
              createdAt: new Date().toISOString(),
              chapterId: 5,
              authorId: '33',
              author: { id: '11', name: 'Chris Reader' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 15,
              content: 'So immersive!',
              createdAt: new Date().toISOString(),
              chapterId: 5,
              authorId: '33',
              author: { id: '11', name: 'Pat Honey' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
        {
          id: 6,
          title: 'The Return',
          author: 'Jane Writer',
          notes: '',
          content: 'Returning home...',
          privacy: 'Private',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2300,
          comments: [
            {
              id: 16,
              content: 'Touching ending.',
              createdAt: new Date().toISOString(),
              chapterId: 6,
              authorId: '33',
              author: { id: '11', name: 'Taylor Buzz' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 17,
              content: 'Loved the journey.',
              createdAt: new Date().toISOString(),
              chapterId: 6,
              authorId: '33',
              author: { id: '11', name: 'Morgan Hive' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 18,
              content: 'Beautiful story.',
              createdAt: new Date().toISOString(),
              chapterId: 6,
              authorId: '33',
              author: { id: '11', name: 'Jamie Nectar' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
      ],
      comments: [],
      collaborators: [
        { id: '44', name: 'Alex Friend' },
        { id: '33', name: 'Sam Bee' },
      ],
    },
    // Book 3
    {
      id: 3,
      title: "Queen's Secret",
      author: 'Jane Writer',
      genre: 'Drama',
      category: 'Fiction',
      description: 'A tale of secrets in the hive.',
      coverImage: '/default-book-cover.png',
      privacy: 'Public',
      // lastEditedBy: 'user-1',
      createdAt: new Date().toISOString(),
      publishedAt: undefined,
      updatedAt: new Date().toISOString(),
      status: 'In Progress',
      wordCount: 26000,
      userId: 'user-1',
      chapters: [
        {
          id: 7,
          title: 'The Whisper',
          author: 'Jane Writer',
          notes: '',
          content: 'A secret is revealed...',
          privacy: 'Public',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2100,
          comments: [
            {
              id: 19,
              content: 'Intriguing!',
              createdAt: new Date().toISOString(),
              chapterId: 7,
              authorId: '33',
              author: { id: '11', name: 'Robin Flower' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 20,
              content: "Can't wait for the next chapter.",
              createdAt: new Date().toISOString(),
              chapterId: 7,
              authorId: '33',
              author: { id: '11', name: 'Casey Pollen' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 21,
              content: 'So mysterious!',
              createdAt: new Date().toISOString(),
              chapterId: 7,
              authorId: '33',
              author: { id: '11', name: 'Drew Clover' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
        {
          id: 8,
          title: 'The Plan',
          author: 'Jane Writer',
          notes: '',
          content: 'A plan is set in motion...',
          privacy: 'Public',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2200,
          comments: [
            {
              id: 22,
              content: 'Very clever.',
              createdAt: new Date().toISOString(),
              chapterId: 8,
              authorId: '33',
              author: { id: '11', name: 'Sky Willow' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 23,
              content: 'Excited to see what happens.',
              createdAt: new Date().toISOString(),
              chapterId: 8,
              authorId: '33',
              author: { id: '11', name: 'Alex Friend' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 24,
              content: 'Great writing.',
              createdAt: new Date().toISOString(),
              chapterId: 8,
              authorId: '33',
              author: { id: '11', name: 'Sam Bee' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
        {
          id: 9,
          title: 'The Reveal',
          author: 'Jane Writer',
          notes: '',
          content: 'The secret comes out...',
          privacy: 'Public',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'In Progress',
          wordCount: 2300,
          comments: [
            {
              id: 25,
              content: "Wow, didn't see that coming!",
              createdAt: new Date().toISOString(),
              chapterId: 9,
              authorId: '33',
              author: { id: '11', name: 'Chris Reader' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 26,
              content: 'Amazing twist.',
              createdAt: new Date().toISOString(),
              chapterId: 9,
              authorId: '33',
              author: { id: '11', name: 'Pat Honey' },
              parentId: undefined,
              replies: [],
            },
            {
              id: 27,
              content: 'Loved it!',
              createdAt: new Date().toISOString(),
              chapterId: 9,
              authorId: '33',
              author: { id: '11', name: 'Taylor Buzz' },
              parentId: undefined,
              replies: [],
            },
          ],
        },
      ],
      comments: [],
      collaborators: [
        { id: '44', name: 'Alex Friend' },
        { id: '44', name: 'Sam Bee' },
      ],
    },
  ],
  friends: [
    { id: '1', name: 'Alex Friend' },
    { id: '2', name: 'Sam Bee' },
    { id: '3', name: 'Chris Reader' },
    { id: '4', name: 'Pat Honey' },
    { id: '5', name: 'Taylor Buzz' },
    { id: '6', name: 'Morgan Hive' },
    { id: '7', name: 'Jamie Nectar' },
    { id: '8', name: 'Robin Flower' },
    { id: '9', name: 'Casey Pollen' },
    { id: '10', name: 'Drew Clover' },
    { id: '11', name: 'Sky Willow' },
    { id: '12', name: 'Jordan Leaf' },
  ],
  receivedRequests: [
    {
      id: 'req-1',
      from: { id: 'user-14', name: 'Taylor Sun' },
      fromId: 'user-14',
      toId: 'user-1',
      status: 'pending',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'req-2',
      from: { id: 'user-15', name: 'Morgan Dew' },
      fromId: 'user-15',
      toId: 'user-1',
      status: 'pending',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'req-3',
      from: { id: 'user-16', name: 'Casey Rain' },
      fromId: 'user-16',
      toId: 'user-1',
      status: 'pending',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'req-4',
      from: { id: 'user-17', name: 'Sky Blue' },
      fromId: 'user-17',
      toId: 'user-1',
      status: 'pending',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'req-5',
      from: { id: 'user-18', name: 'Robin Sun' },
      fromId: 'user-18',
      toId: 'user-1',
      status: 'pending',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'req-6',
      from: { id: 'user-19', name: 'Jamie Cloud' },
      fromId: 'user-19',
      toId: 'user-1',
      status: 'pending',
      createdAt: new Date().toISOString(),
    },
  ],

  notifications: [
    ...Array.from({ length: 27 }, (_, i) => ({
      id: `notif-${i + 1}`,
      type: 'comment',
      message: `New comment #${i + 1} on your chapter`,
      date: new Date().toISOString(),
      read: false,
    })),
    ...Array.from({ length: 6 }, (_, i) => ({
      id: `notif-req-${i + 1}`,
      type: 'friend_request',
      message: `New friend request from user-${14 + i}`,
      date: new Date().toISOString(),
      read: false,
    })),
  ],
};
