import { BookType } from './types/books.type';

export const userBooks: BookType[] = [
  {
    id: 1,
    title: 'The Honey Trail',
    author: 'Jane Writer',
    genre: 'Adventure',
    category: 'Fiction',
    privacy: 'Public',
    cover: '',
    lastEditedBy: 1,
    description: 'A book about the thing that went and did the other thing.',
    createdAt: '2025-07-01T10:00:00Z',
    publishedAt: '2025-07-10T10:00:00Z',
    updatedAt: '2025-07-30T12:00:00Z',
    status: 'In Progress',
    wordCount: 32000,
    chapters: [
      {
        id: 1,
        title: 'A New Hive',
        author: 'John Doe',
        notes: 'Intro to the world',
        content: 'Once upon a time...',
        privacy: 'Public',
        createdAt: '2025-07-01T10:00:00Z',
        updatedAt: '2025-07-01T12:00:00Z',
        status: 'In Progress',
        wordCount: 2500,
        comments: [
          {
            id: 1,
            authorId: 1,
            content: 'Great start!',
            createdAt: '2025-07-01T13:00:00Z',
            chapterId: 1,
            author: { id: 2, name: 'Alex Friend' },
            replies: [
              {
                id: 1,
                authorId: 2,
                content: 'I agree, very engaging!',
                createdAt: '2025-07-01T14:00:00Z',
                chapterId: 1,
                author: { id: 2, name: 'Alex Friend' },
                replies: [
                  {
                    id: 1,
                    authorId: 3,
                    content: 'Looking forward to more!',
                    createdAt: '2025-07-01T15:00:00Z',
                    chapterId: 1,
                    author: { id: 3, name: 'Sam Bee' },
                    replies: [],
                  },
                ],
              },
              {
                id: 5,
                authorId: 2,
                content: 'I agree, very engaging!',
                createdAt: '2025-07-01T14:00:00Z',
                chapterId: 1,
                author: { id: 2, name: 'Alex Friend' },
                replies: [
                  {
                    id: 1,
                    authorId: 3,
                    content: 'Looking forward to more!',
                    createdAt: '2025-07-01T15:00:00Z',
                    chapterId: 1,
                    author: { id: 3, name: 'Sam Bee' },
                    replies: [],
                  },
                ],
              },
            ],
          },
          {
            id: 2,
            authorId: 1,
            content: 'Great start! add more of something',
            createdAt: '2025-07-01T13:00:00Z',
            chapterId: 1,
            author: { id: 2, name: 'Alex Friend' },
            replies: [
              {
                id: 1,
                authorId: 2,
                content: 'I agree, very engaging!',
                createdAt: '2025-07-01T14:00:00Z',
                chapterId: 1,
                author: { id: 2, name: 'Alex Friend' },
                replies: [
                  {
                    id: 1,
                    authorId: 3,
                    content: 'Looking forward to more!',
                    createdAt: '2025-07-01T15:00:00Z',
                    chapterId: 1,
                    author: { id: 3, name: 'Sam Bee' },
                    replies: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 2,
        title: 'Chapter 2',
        author: 'John Doe',
        notes: 'Intro to the world',
        content: 'Once upon a time...',
        privacy: 'Public',
        createdAt: '2025-07-01T10:00:00Z',
        updatedAt: '2025-07-01T12:00:00Z',
        status: 'In Progress',
        wordCount: 2500,
        comments: [
          {
            id: 1,
            authorId: 2,
            content: 'Great start!',
            createdAt: '2025-07-01T13:00:00Z',
            chapterId: 1,
            author: { id: 2, name: 'Alex Friend' },
            replies: [],
          },
        ],
      },
    ],
    comments: [
      {
        id: 2,
        authorId: 2,
        content: 'Love this book!',
        createdAt: '2025-07-02T09:00:00Z',
        chapterId: 1,
        author: { id: 3, name: 'Sam Bee' },
        replies: [],
      },
    ],
    collaborators: [
      { id: 2, name: 'Alex Friend' },
      { id: 3, name: 'Sam Bee' },
    ],
  },
  {
    id: 2,
    title: 'Lord of the Rings: Fellowship of the Ring and More',
    author: 'Sam Bee',
    genre: 'Memoir',
    category: 'Adventure',
    privacy: 'Private',
    cover: '/default-book-cover.png',
    lastEditedBy: 1,
    createdAt: '2025-07-05T10:00:00Z',
    publishedAt: undefined,
    updatedAt: '2025-07-28T15:00:00Z',
    status: 'In Progress',
    wordCount: 21000,
    chapters: [],
    comments: [],
    collaborators: [{ id: 1, name: 'Jane Writer' }],
  },
];

export const friendsBooks: BookType[] = [
  {
    id: 3,
    title: 'Hive Mind',
    author: 'Alex Friend',
    genre: 'Sci-Fi',
    category: 'Science',
    privacy: 'Public',
    cover: '/default-book-cover.png',
    lastEditedBy: 2,
    createdAt: '2025-07-15T10:00:00Z',
    publishedAt: '2025-07-20T10:00:00Z',
    updatedAt: '2025-07-31T09:00:00Z',
    status: 'In Progress',
    wordCount: 15000,
    chapters: [
      {
        id: 2,
        author: 'John Doe',
        title: 'The Swarm',
        notes: '',
        content: 'The bees gathered...',
        privacy: 'Public',
        createdAt: '2025-07-15T10:00:00Z',
        updatedAt: '2025-07-15T12:00:00Z',
        status: 'In Progress',
        wordCount: 2000,
        comments: [],
      },
    ],
    comments: [
      {
        id: 3,
        authorId: 1,
        content: 'Fascinating concept!',
        createdAt: '2025-07-16T11:00:00Z',
        chapterId: 2,
        author: { id: 1, name: 'Jane Writer' },
        replies: [],
      },
    ],
    collaborators: [{ id: 1, name: 'Jane Writer' }],
  },
];
