import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/header/navbar';
import { Toaster } from '@/components/ui/sonner';
import Footer from '@/components/footer';
import NotificationInitializer from '@/lib/providers/notificationProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="bg-gradient-to-b from-yellow-200 via-yellow-400 to-yellow-500 min-h-screen">
          <NotificationInitializer />
          <Navbar />
          <div className="mb-4"></div>
          {children}
          <Footer />
          <Toaster richColors />
        </div>
      </body>
    </html>
  );
}
