export const CATEGORIES = [
  'Fiction',
  'Non-Fiction',
  'Poetry',
  'Memoir',
  'Biography',
  'Essay',
  'Self-Help',
  'Academic',
  'Journalism',
  'Other',
];

export const GENRES = [
  'Action & Adventure',
  'Children',
  'Classic Literature',
  'Comedy',
  'Contemporary',
  'Crime',
  'Dark Fiction',
  'Drama',
  'Dystopian',
  'Fantasy',
  'Graphic Novel',
  'Historical Fiction',
  'Horror',
  'Literary Fiction',
  'Mystery',
  'Mythology & Folklore',
  'Paranormal',
  'Romance',
  'Satire',
  'Science Fiction',
  'Slice of Life',
  'Supernatural',
  'Thriller',
  'Urban Fantasy',
  'Western',
  'Young Adult',
  'Other',
];

export const PRIVACY_OPTIONS = [
  { value: 'PUBLIC', label: 'Public', description: 'Anyone can read' },
  { value: 'PRIVATE', label: 'Private', description: 'Only you' },
  { value: 'FRIENDS', label: 'Friends Only', description: 'You + friends' },
] as const;